"""initial schema

Revision ID: 127f256e26b9
Revises: 
Create Date: 2026-03-06 14:44:39.672990
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127f256e26b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dancer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('dancer_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('talam', sa.String(length=100), nullable=True),
    sa.Column('ragam', sa.String(length=100), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_key', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('pipeline_progress', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('aramandi_score', sa.Float(), nullable=True),
    sa.Column('upper_body_score', sa.Float(), nullable=True),
    sa.Column('symmetry_score', sa.Float(), nullable=True),
    sa.Column('rhythm_consistency_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('technique_scores', sa.JSON(), nullable=True),
    sa.Column('patterns', sa.JSON(), nullable=True),
    sa.Column('fatigue_markers', sa.JSON(), nullable=True),
    sa.Column('llm_summary', sa.String(length=8000), nullable=True),
    sa.Column('practice_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_id')
    )
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('dancer_pose', sa.JSON(), nullable=False),
    sa.Column('left_hand', sa.JSON(), nullable=True),
    sa.Column('right_hand', sa.JSON(), nullable=True),
    sa.Column('face', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('center_of_mass_x', sa.Float(), nullable=True),
    sa.Column('center_of_mass_y', sa.Float(), nullable=True),
    sa.Column('weight_distribution', sa.Float(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id')
    )
    op.create_table('joint_angle_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('aramandi_angle', sa.Float(), nullable=True),
    sa.Column('torso_uprightness', sa.Float(), nullable=True),
    sa.Column('arm_extension_left', sa.Float(), nullable=True),
    sa.Column('arm_extension_right', sa.Float(), nullable=True),
    sa.Column('hip_symmetry', sa.Float(), nullable=True),
    sa.Column('all_angles', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id')
    )
    op.create_table('mudra_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('left_hand_mudra', sa.String(length=100), nullable=True),
    sa.Column('right_hand_mudra', sa.String(length=100), nullable=True),
    sa.Column('confidence_left', sa.Float(), nullable=True),
    sa.Column('confidence_right', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mudra_states')
    op.drop_table('joint_angle_states')
    op.drop_table('balance_metrics')
    op.drop_table('frames')
    op.drop_table('analyses')
    op.drop_table('performances')
    op.drop_table('sessions')
    op.drop_table('dancers')
    # ### end Alembic commands ###
