"""Add SAM 2 tracking tables

Revision ID: 9ac63380e2ba
Revises: f2b3c4d5e6a7
Create Date: 2026-03-27 18:11:07.853753
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac63380e2ba'
down_revision: Union[str, None] = 'f2b3c4d5e6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('dancer_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('mask_iou', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracking_frames_perf_dancer_ts', 'tracking_frames', ['performance_id', 'dancer_index', 'timestamp_ms'], unique=False)
    op.create_index(op.f('ix_tracking_frames_performance_id'), 'tracking_frames', ['performance_id'], unique=False)
    op.drop_constraint('balance_metrics_frame_id_fkey', 'balance_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'balance_metrics', 'frames', ['frame_id'], ['id'])
    op.drop_constraint('joint_angle_states_frame_id_fkey', 'joint_angle_states', type_='foreignkey')
    op.create_foreign_key(None, 'joint_angle_states', 'frames', ['frame_id'], ['id'])
    op.drop_constraint('mudra_states_frame_id_fkey', 'mudra_states', type_='foreignkey')
    op.create_foreign_key(None, 'mudra_states', 'frames', ['frame_id'], ['id'])
    op.add_column('performances', sa.Column('start_timestamp_ms', sa.Integer(), nullable=True))
    op.add_column('performances', sa.Column('click_prompts', sa.JSON(), nullable=True))
    op.drop_constraint('performances_session_id_fkey', 'performances', type_='foreignkey')
    op.drop_constraint('performances_dancer_id_fkey', 'performances', type_='foreignkey')
    op.create_foreign_key(None, 'performances', 'dancers', ['dancer_id'], ['id'])
    op.create_foreign_key(None, 'performances', 'sessions', ['session_id'], ['id'])
    op.drop_constraint('sessions_dancer_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'dancers', ['dancer_id'], ['id'])
    # ### end Alembic commands ###
    op.execute(
        "UPDATE performances SET status = 'failed', "
        "error = 'Pipeline upgraded to SAM 2 tracking — please re-upload this video' "
        "WHERE status IN ('queued', 'detecting', 'awaiting_selection')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_dancer_id_fkey', 'sessions', 'dancers', ['dancer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'performances', type_='foreignkey')
    op.drop_constraint(None, 'performances', type_='foreignkey')
    op.create_foreign_key('performances_dancer_id_fkey', 'performances', 'dancers', ['dancer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('performances_session_id_fkey', 'performances', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('performances', 'click_prompts')
    op.drop_column('performances', 'start_timestamp_ms')
    op.drop_constraint(None, 'mudra_states', type_='foreignkey')
    op.create_foreign_key('mudra_states_frame_id_fkey', 'mudra_states', 'frames', ['frame_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'joint_angle_states', type_='foreignkey')
    op.create_foreign_key('joint_angle_states_frame_id_fkey', 'joint_angle_states', 'frames', ['frame_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'balance_metrics', type_='foreignkey')
    op.create_foreign_key('balance_metrics_frame_id_fkey', 'balance_metrics', 'frames', ['frame_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tracking_frames_performance_id'), table_name='tracking_frames')
    op.drop_index('ix_tracking_frames_perf_dancer_ts', table_name='tracking_frames')
    op.drop_table('tracking_frames')
    # ### end Alembic commands ###
